# Generated by Django 5.0.1 on 2024-01-29 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=90)),
                ('telefono', models.IntegerField()),
                ('rut_medico', models.IntegerField()),
                ('dv_medico', models.CharField(max_length=1)),
                ('especialidad', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=90)),
                ('telefono', models.IntegerField()),
                ('rut_paciente', models.IntegerField()),
                ('dv_paciente', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=90)),
                ('telefono', models.IntegerField()),
                ('rut_secretaria', models.IntegerField()),
                ('dv_secretaria', models.CharField(max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('atencion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atencion')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(max_length=200)),
                ('dias_semana', models.CharField(max_length=200)),
                ('finalizacion_contrato', models.DateTimeField()),
                ('rut_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='rut_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='rut_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
    ]
