# Generated by Django 5.0.1 on 2024-01-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='hora_fin',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
