# Generated by Django 5.0.1 on 2024-01-31 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_especialidad_alter_medico_especialidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidad',
            old_name='especialidad',
            new_name='nombre_esp',
        ),
    ]
