# Generated by Django 5.0.1 on 2024-01-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_especialidad_especialidad_nombre_esp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='rut_medico',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut_paciente',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='email',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='rut_secretaria',
            field=models.IntegerField(unique=True),
        ),
    ]
